### ISSUE TITLE
'Item with the same key...' error  on initialisation of Deveroom - binding could not be discovered.

### ISSUE THREAD

**Issue by jameslavery** [specsolutions/deveroom-visualstudio#32] opened 2019-05-17 14:06 UTC
I'm having a problem with Deveroom - it shows the error below, and (as the error says), navigation, step completion etc. are disabled.

I'd previously had the SpecFlow extension installed. I've now uninstalled and reinstalled Deveroom but still have the problem.

Any thoughts? This is on VS2019.

> Info: OnActivityStarted: Starting Deveroom...
> Info: CreateProjectScope: Initializing project: PureGym.App.Member.SpecTests
> Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
> Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v2.1,SpecFlow:3.0.155-beta
> Warning: InvokeDiscovery: Error during binding discovery. 
> Command executed:
>   C:\Users\jameslavery\source\repos\puregym.mobile\test\PureGym.App.Member.SpecTests\bin\Debug\netcoreapp2.1> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\JAMESLAVERY\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_C81F5ABF\EXTENSIONS\LQ2OLSAB.GAG\Connectors\V2\deveroom-specflow-v2.dll discovery C:\Users\jameslavery\source\repos\puregym.mobile\test\PureGym.App.Member.SpecTests\bin\Debug\netcoreapp2.1\PureGym.App.Member.SpecTests.dll C:\Users\jameslavery\source\repos\puregym.mobile\test\PureGym.App.Member.SpecTests\specflow.json
> Exit code: 3
> Message: 
> Error: An item with the same key has already been added. Key: Unity.Abstractions
> Exception: System.ArgumentException
> StackTrace:
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at McMaster.NETCore.Plugins.Loader.AssemblyLoadContextBuilder.AddManagedLibrary(ManagedLibrary library)
>    at McMaster.NETCore.Plugins.Loader.DependencyContextExtensions.AddDependencyContext(AssemblyLoadContextBuilder builder, DependencyContext dependencyContext)
>    at Deveroom.VisualStudio.SpecFlowConnector.Discovery.LoadContextHelper.AddDependencyContextWithCompileDeps(AssemblyLoadContextBuilder builder, String depsFilePath) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\LoadContextHelper.cs:line 82
>    at Deveroom.VisualStudio.SpecFlowConnector.Discovery.LoadContextHelper.CreateLoadContext(String baseDir, AssemblyName mainAssemblyName, PluginLoaderOptions loaderOptions, IEnumerable`1 preferDefaultLoadContextForAssemblies, IEnumerable`1 privateAssemblies) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\LoadContextHelper.cs:line 38
>    at Deveroom.VisualStudio.SpecFlowConnector.Discovery.LoadContextHelper.CreateLoadContext(String assemblyFile) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\LoadContextHelper.cs:line 18
>    at Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process() in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\DiscoveryProcessor.cs:line 20
>    at Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector\ConsoleRunner.cs:line 32
> 
> Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled.

**Comment by gasparnagy** [comment] 2019-05-22 08:36
Thx for submitting this. This is pretty bad, because the problem seems to be in the `AddDependencyContext` method of the (called at from [this line](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Deveroom.VisualStudio.SpecFlowConnector.V2/Discovery/LoadContextHelper.cs#L81)) `McMaster.NETCore.Plugins` library.
What we probably need to do is to re-implement the method in a way that it better checks the dictionary, like I did with [`AddCompileDependencies`](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Deveroom.VisualStudio.SpecFlowConnector.V2/Discovery/LoadContextHelper.cs#L87).
I will check.

**Comment by gasparnagy** [comment] 2019-06-24 11:27
The fix will be released in a few days

**Closed** 2019-06-24 11:27 UTC
Labels: bug

**Comment by hallipr** [comment] 2019-12-12 00:56
I'm seeing this issue in v1.5.0:
```
Error: An item with the same key has already been added. Key: Cosmos.CRTCompat
Exception: System.ArgumentException
StackTrace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at McMaster.NETCore.Plugins.Loader.AssemblyLoadContextBuilder.AddNativeLibrary(NativeLibrary library)
   at McMaster.NETCore.Plugins.Loader.DependencyContextExtensions.AddDependencyContext(AssemblyLoadContextBuilder builder, DependencyContext dependencyContext, Boolean includeCompileLibraries)
   at McMaster.NETCore.Plugins.Loader.DependencyContextExtensions.AddDependencyContext(AssemblyLoadContextBuilder builder, String depsFilePath, Boolean includeCompileLibraries)
   at McMaster.NETCore.Plugins.PluginLoader.CreateLoadContext(String baseDir, PluginConfig config, Type[] sharedTypes, PluginLoaderOptions loaderOptions)
   at McMaster.NETCore.Plugins.PluginLoader..ctor(PluginConfig config, String baseDir, Type[] sharedTypes, PluginLoaderOptions loaderOptions)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, PluginLoaderOptions loaderOptions)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process() in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\DiscoveryProcessor.cs:line 22
   at Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args) in W:\Deveroom\deveroom-visualstudio-prod\community\Deveroom.VisualStudio.SpecFlowConnector\ConsoleRunner.cs:line 32
```

**Comment by gasparnagy** [comment] 2019-12-13 15:42
@hallipr Could you please create a new issue about this (with a reference to this), so that it is easier to track it. Unfortunately these issues are pretty hard to nail down. If you could maybe create a small repro, that would be really useful. An ~empty project with a same references like yours, with a single feature file and a single empty step definition should be enough to reproduce the problem. You can simply attach it as a zip to the issue. Thx!
