### ISSUE TITLE
Visual Studio freezes and restart when adding a new feature file to an SDK-style project

### ISSUE THREAD

**Issue by iceoz** [specsolutions/deveroom-visualstudio#46] opened 2019-07-12 17:18 UTC
Every new feature my visual studio freezes and restart, how to solve this? where i can get logs for this errors?

**Comment by okyrylenko** [comment] 2019-07-12 17:57
the same here. I would suggest to give another title to this issue. The current title "Help" is not very explicit of what the issue is

**Comment by gasparnagy** [comment] 2019-07-12 18:45
@iceoz @okyrylenko Could you please share more information on the context (which VS version, which Deveroom version, what other non-default VS extensions you have installer) and on how the freeze happens (what do you do to let it happen). If you can share a small screen-recording that's also very useful.

For accessing the log and trace files and on how to try out with an older version, please check the [Troubleshooting](https://github.com/specsolutions/deveroom-visualstudio/wiki/Troubleshooting) page.

**Comment by gasparnagy** [comment] 2019-07-22 07:55
@iceoz @okyrylenko do you still have this issue?

**Comment by psehmbi** [comment] 2019-07-26 07:47
I am having the same issue:
VS version: 16.1.0 (2019)
Deveroom version 1.4.1

Deveroom is the only non-standard extension I have installed.

To reproduce you just simply add a new feature file. Visual studio will freeze and then restart and the banner is displayed: "A previous session ended unexpectedly. Disabling the extension Deveroom for SpecFlow (Visual Studio 2019) 1.4.1 might help."

This happens every time a new feature file is added.

**Comment by gasparnagy** [comment] 2019-07-30 06:28
@psehmbi And do you see anything strange in the log (see [Troubleshooting page](https://github.com/specsolutions/deveroom-visualstudio/wiki/Troubleshooting))?

**Comment by psehmbi** [comment] 2019-07-31 15:15
@gasparnagy There is nothing sinister looking in the output panel, and when the issue occurs nothing new is written (presumably because Visual Studio crashes before anything can be written). In the log file, there is an entry for `Missing [assembly:RuntimePlugin] attribute in TechTalk.SpecFlow.xUnit.SpecFlowPlugin, Version=3.0.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41.` Not sure if that is related.

I have gone back a few versions and the problem starts happening in `v1.3.0`. `v1.2.1` does not exhibit this behaviour. If you need any more information let me know.

**Comment by gasparnagy** [comment] 2019-08-01 07:32
@psehmbi thx for the info. The missing attribute is not related. I will review the changes in 1.3... Unfortunately that was a bigger change, but anyway. At least something to start with. 
Would it be possible to do an online debugging session with you? Like we would have an online call and I would help you to debug Deveroom to find out where the problem is.

**Comment by psehmbi** [comment] 2019-08-01 07:35
Sure @gasparnagy let me know what you need from me.

**Comment by gasparnagy** [comment] 2019-08-01 07:48
@psehmbi pls send a mail to gaspar at specsolutions.eu and we will discuss it over there.

**Comment by gasparnagy** [comment] 2019-08-04 20:34
Fixed in v1.4.2. Thank you @psehmbi for the help.

**Closed by gasparnagy** 2019-08-04 20:34 UTC
Labels: bug

**Comment by psehmbi** [comment] 2019-08-05 13:02
Can confirm working in 1.4.2 👍
